### ISSUE TITLE
Dragging Interface

### ISSUE THREAD

**Issue by MichelleArk** [alecjacobson/geometry-processing-deformation#14]
I'm having a little trouble figuring out how to actually drag control points after clicking to create them. Dragging seems to just interact with the scene as per normal (ie rotate the model). When I print out the deformation values (`bc`) are when fed into `biharmonic_solve` I get all 0 vectors. Any tips?

**Comment by alecjacobson** [comment]
@MichelleArk you closed this. Is it all sorted out?

**Comment by MichelleArk** [comment]
Yes, all good. Had a feeling I'd figure it out right after posting an issue.
