### ISSUE TITLE
Derivation of (20)

### ISSUE THREAD

**Issue by aPToul** [alecjacobson/geometry-processing-deformation#30]
Hi, 

I was wondering how to derive Equation (20) in the Read Me. I made an attempt and came out with some questions:

**1** Are these the gradients we care about along each edge?
`Slope Along Edge_ij = (v_i - v_j) / || v_i - v_j ||`

**2** Are we assuming the edge lengths before and after deformation are nearly equal?

**3** Do we assume the cotangent weights (and thus gradients) do not change significantly within each triangle after deformation? Is that what is meant by constant in the ReadMe?

**4** I'm not sure how we inject the cotangent weights in the energy. Below is my work:
```Energy = ∫ || ∇ x - ∇ y ||^2 dA
Summation over all edges, using the gradients I suggested above
= ∑ || Slope_Before - Slope_After ||^2 * Edge_Length
Assume edge lengths are equal before and after deformation
~ ∑ || Difference_Before - Difference_After||^2

**Comment by alecjacobson** [comment]
These are good questions. Thanks for writing them in such an organized way.

1. No, this is related to the answers to 3 and 4.

2. Also no, ARAP can measure wild changes in scale, though you can argue that it's not the best measure of distortion when triangles shrink to near-zero area.

3/4. One way to think of ARAP is that we're computing a deformation field d over
the original surface. A deformation field is described by a scalar field for the
displacement in x-coordinate, another scalar field for the displace in
y-coordinate, and one more the z-coordinate. Each of these scalar fields is
represented on the computer using a piecewise linear function with interpolated
values at vertices (recall the "hat functions"). So, for example, the value of
the displacement field at some point p anywhere on the mesh
will be:

d(p) = ∑_{i ∈ V} di φi(p)

So the Gradient of each piecewise linear will be _constant_ inside each
triangle. Consider a the gradient at a single point p in a triangle f, will be
the sum of the gradients of the displacement field contributions of each corner
of the triangle

∇d(p) = ∇(∑_{i ∈ f} di φi(P)

We can move the gradient inside the sum, we'll use this later:

(1) ∇d(p) = ∑_{i ∈ f} di ∇φi(P)

For our deformation energy, we start with the discrete dirichlet energy which
sums up the integrated squared norm of the gradient over all triangles in the
mesh:

½∑_{f ∈ F} ∫_f ‖∇d(p)‖² dA

We can expand this by using the fact that d = x - X (where x are the _new_
positions and X are the _old_ positions, each is again will be discretized using
piecewise linear functions):

½∑_{f ∈ F} ∫_f ‖∇d(p)‖² dA 
= ½∑_{f ∈ F} ∫_f ‖∇x(p) - ∇X(p)‖² dA
= ½∑_{f ∈ F} ∫_f ‖ (∑_{i ∈ f} xi ∇φi(p)) - (∑_{j ∈ f} Xj ∇φj(p))‖² dA


We can now understand Dirichlet energy as a comparison of gradients of the
embedding before (∇x) and after (∇X) the deformation. We'll make it rotation
invariant by adding a best fit rotation:

½ ∑_{f ∈ F} ∫_f ‖ (∑_{i ∈ f} xi ∇φi(p)) - R(∑_{j ∈ f} Xj ∇φj(p))‖² dA

xi, R and xj are all constants (in any triangle f, anyway) with respect to the
integration point p, so we can expand this squared norm and move the integral
inside:

∑_{f ∈ F} ∫_f 
  ½‖∑_{i ∈ f} xi ∇φi(p)‖² - 
  (∑_{i ∈ f} xi ∇φi(p))ᵀR(∑_{j ∈ f} Xj ∇φj(p)) + 
  (∑_{j ∈ f} Xj ∇φj(p))ᵀRᵀR(∑_{j ∈ f} Xj ∇φj(p)) dA
= 
∑_{f ∈ F}  
  ½∑_{i ∈ f}∑_{j ∈ f} xi xj ∫_f ∇φi(p)ᵀ ∇φj(p) dA - 
  ∑_{i ∈ f} ∑_{j ∈ f} xi Xj ∫_f ∇φi(p))ᵀR∇φj(p)) dA + 
  [contsant term with respect to x]

Phew, it's getting complicated, but we already have our first cotangent
spotting. In the first term (quadratic in x) we see:

∫_f ∇φi(p)ᵀ ∇φj(p) dA

This is hopefully familiar.

Cotangents arise from the second term (linear term in x), too, but for that I'll
defer back to the readme.

**Comment by alecjacobson** [comment]
precisely.

**Comment by aPToul** [comment]
Just a last question: How do we convert back from the (x_i * x_j) in your last line (ignoring R for now) to the (v_i - v_j) in (20)?

It is my understand that x as we defined it here is the same as v there. When I try to work backwards from ||(v_i − v_j) − (v̂_i − v̂_j)||^2 I get more terms than in our energy from your last lane:

½ ∑_{i ∈ f} ∑_{j ∈ f} c_ij (v_i * v_j) dA - ∑_{i ∈ f} ∑_{j ∈ f} (v_i v̂_j) <Integral> dA + Constant

**Comment by alecjacobson** [comment]
Sorry, it's hard to do math in these text areas. I intended that x_i is the 3D position of the ith vertex.

**Comment by aPToul** [comment]
I updated my question to reflect that, I still find it hard to convert from dot products to differences

**Comment by alecjacobson** [comment]
|| (x_i − x_j) − (X_i − X_j) ||^2
= ((x_i − x_j) − (X_i − X_j)) . ((x_i − x_j) − (X_i − X_j))
= x_i^2 - 2 x_i x_j - 2x_i X_i + 2x_i X_j - 2x_jX_i+ 2x_jX_j + constants...
