### ISSUE TITLE
ARAP Energy term

### ISSUE THREAD

**Issue by bsvineethiitg** [alecjacobson/geometry-processing-deformation#35]
Hi. I have a question regarding the ARAP energy term in the assignment. 

So, we would like to have the new transformed points x to be as close as possible to some rigid transformation (R_k, t_k) from x_hat (the original points). 

Why would we prefer then to use the gradient-based energy for ARAP (i.e., \int ||grad(x) - grad(R_k x_hat + t_k)||^2) instead of an energy based on the actual difference of the rigid transform (i.e., \int ||x - (R_k x_hat + t_k)||^2)?

**Comment by alecjacobson** [comment]
There are a couple ways to consider this.

We want this rigidity property to hold not just _globally_ (i.e., the entire shape is rotated) but also _locally_ (i.e., just the hand rotates). So the best fit rigid transformation has to be applied locally. Hence the optimal rotations per vertex ring.

Can you recall from the ICP assignment what happened to the optimal translation term?

**Comment by bsvineethiitg** [comment]
Thank you, Prof. Jacobson. I have got this cleared in the guest lecture.
